<?php
/**
 * ACF Template 4 Settings - Field Groups
 * 
 * @package kaziki
 */

if (!defined('ABSPATH')) {
    exit;
}

if (function_exists('acf_add_local_field_group')) {
    
    acf_add_local_field_group(array(
        'key' => 'group_template4_settings',
        'title' => 'Template 4 Settings',
        'fields' => array(
            // Header Tab
            array(
                'key' => 'field_t4_header_tab',
                'label' => 'Header',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_header_position',
                'label' => 'Header position',
                'name' => 't4_header_position',
                'type' => 'select',
                'choices' => array(
                    'fixed' => 'fixed',
                    'static' => 'static',
                ),
                'default_value' => 'static',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_header_color',
                'label' => 'Header color',
                'name' => 't4_header_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_header_main',
                'label' => 'Header HTML main',
                'name' => 't4_header_main',
                'type' => 'textarea',
            ),
            array(
                'key' => 'field_t4_logo',
                'label' => 'Logo',
                'name' => 't4_logo',
                'type' => 'image',
                'return_format' => 'url',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_favicon',
                'label' => 'Favicon',
                'name' => 't4_favicon',
                'type' => 'image',
                'return_format' => 'url',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_og_image',
                'label' => 'OG image',
                'name' => 't4_og_image',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'wrapper' => array('width' => '33'),
            ),
            
            // Menu
            array(
                'key' => 'field_t4_menu',
                'label' => 'Menu',
                'name' => 't4_menu',
                'type' => 'repeater',
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_t4_menu_name',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_t4_menu_link',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'url',
                    ),
                ),
            ),
            
            // Casinos Tab
            array(
                'key' => 'field_t4_casinos_tab',
                'label' => 'Casinos',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_casino_list',
                'label' => 'Casino List',
                'name' => 't4_casino_list',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Casino',
                'sub_fields' => array(
                    array(
                        'key' => 'field_t4_casino_logo',
                        'label' => 'Logo',
                        'name' => 'logo',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                    ),
                    array(
                        'key' => 'field_t4_casino_name',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_t4_casino_bonus',
                        'label' => 'Bonus',
                        'name' => 'bonus',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_t4_casino_list_desc',
                        'label' => 'List',
                        'name' => 'list',
                        'type' => 'wysiwyg',
                        'tabs' => 'visual',
                        'media_upload' => 0,
                        'toolbar' => 'basic',
                    ),
                    array(
                        'key' => 'field_t4_casino_rating',
                        'label' => 'Rating',
                        'name' => 'rating',
                        'type' => 'number',
                        'min' => 0,
                        'max' => 10,
                        'step' => 0.1,
                    ),
                    array(
                        'key' => 'field_t4_casino_link',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_t4_casino_border',
                        'label' => 'Border',
                        'name' => 'border',
                        'type' => 'color_picker',
                        'instructions' => 'Optional border color for highlighted casinos',
                    ),
                ),
            ),
            
            // Author Tab
            array(
                'key' => 'field_t4_author_tab',
                'label' => 'Author',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_author_name',
                'label' => 'Author name',
                'name' => 't4_author_name',
                'type' => 'text',
                'instructions' => 'Author name to display',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_author_avatar',
                'label' => 'Author avatar',
                'name' => 't4_author_avatar',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_author_color',
                'label' => 'Author box background',
                'name' => 't4_author_color',
                'type' => 'color_picker',
                'default_value' => '#f3f3f3',
                'wrapper' => array('width' => '33'),
            ),
            
            // Colors Tab
            array(
                'key' => 'field_t4_colors_tab',
                'label' => 'Colors',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_main_color',
                'label' => 'Main color',
                'name' => 't4_main_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_second_color',
                'label' => 'Second color',
                'name' => 't4_second_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_btn_color',
                'label' => 'Button color',
                'name' => 't4_btn_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_btn_color_text',
                'label' => 'Button color text',
                'name' => 't4_btn_color_text',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_btn2_color',
                'label' => 'Button2 color',
                'name' => 't4_btn2_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_btn2_color_text',
                'label' => 'Button2 color text',
                'name' => 't4_btn2_color_text',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_bg_color',
                'label' => 'Background color (body)',
                'name' => 't4_bg_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_border_colors',
                'label' => 'Border colors',
                'name' => 't4_border_colors',
                'type' => 'color_picker',
                'default_value' => '#7cae8d',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_text_color',
                'label' => 'Text color',
                'name' => 't4_text_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_link_color',
                'label' => 'Link color',
                'name' => 't4_link_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_table_odd',
                'label' => 'Table odd background',
                'name' => 't4_table_odd',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_table_even',
                'label' => 'Table even background',
                'name' => 't4_table_even',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_author_color',
                'label' => 'Author color',
                'name' => 't4_author_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_cs_bg',
                'label' => 'Casino items button bg',
                'name' => 'cs_bg',
                'type' => 'color_picker',
                'default_value' => '#28a745',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_cs_color',
                'label' => 'Casino items button color',
                'name' => 'cs_color',
                'type' => 'color_picker',
                'default_value' => '#FFF',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_casino_text_color',
                'label' => 'Casino items text color',
                'name' => 't4_casino_text_color',
                'type' => 'color_picker',
                'default_value' => '#333',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_casino_card_bg',
                'label' => 'Casino items background',
                'name' => 't4_casino_card_bg',
                'type' => 'color_picker',
                'default_value' => '#ffffff',
                'wrapper' => array('width' => '33'),
            ),
            
            // Main Tab
            array(
                'key' => 'field_t4_main_tab',
                'label' => 'Main',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_main_google_font',
                'label' => 'Font family',
                'name' => 't4_main_google_font',
                'type' => 'select',
                'choices' => array(
                    'Arial, sans-serif' => 'Arial, sans-serif',
                    '"Montserrat", sans-serif' => '"Montserrat", sans-serif',
                    '"Inter", sans-serif' => '"Inter", sans-serif',
                    '"Open Sans", sans-serif' => '"Open Sans", sans-serif',
                    '"Cuprum", sans-serif' => '"Cuprum", sans-serif',
                    'sans-serif' => 'sans-serif',
                    'cursive' => 'cursive',
                    'system-ui' => 'system-ui',
                    'monospace' => 'monospace',
                    'math' => 'math',
                ),
                'default_value' => 'Arial, sans-serif',
            ),
            array(
                'key' => 'field_t4_ref_link',
                'label' => 'Ref link',
                'name' => 't4_ref_link',
                'type' => 'url',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_alt_text',
                'label' => 'Alt text',
                'name' => 't4_alt_text',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            
            // Fonts Tab
            array(
                'key' => 'field_t4_fonts_tab',
                'label' => 'Fonts',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_h1',
                'label' => 'h1',
                'name' => 't4_h1',
                'type' => 'number',
                'instructions' => 'РАЗМЕР в \'em\' не в пикселях',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_h2',
                'label' => 'h2',
                'name' => 't4_h2',
                'type' => 'number',
                'instructions' => 'РАЗМЕР в \'em\' не в пикселях',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_h3',
                'label' => 'h3',
                'name' => 't4_h3',
                'type' => 'number',
                'instructions' => 'РАЗМЕР в \'em\' не в пикселях',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_h4',
                'label' => 'h4',
                'name' => 't4_h4',
                'type' => 'number',
                'instructions' => 'РАЗМЕР в \'em\' не в пикселях',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_p',
                'label' => 'p',
                'name' => 't4_p',
                'type' => 'number',
                'instructions' => 'РАЗМЕР в \'px\'',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_li',
                'label' => 'li',
                'name' => 't4_li',
                'type' => 'number',
                'instructions' => 'РАЗМЕР в \'px\'',
                'wrapper' => array('width' => '33'),
            ),
            
            // Footer Tab
            array(
                'key' => 'field_t4_footer_tab',
                'label' => 'Footer',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_footer_text',
                'label' => 'Footer text',
                'name' => 't4_footer_text',
                'type' => 'text',
            ),
            array(
                'key' => 'field_t4_footer_color',
                'label' => 'Footer background',
                'name' => 't4_footer_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_footer_color_text',
                'label' => 'Footer color text',
                'name' => 't4_footer_color_text',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_footer_menu1',
                'label' => 'Footer menu1',
                'name' => 't4_footer_menu1',
                'type' => 'repeater',
                'layout' => 'table',
                'wrapper' => array('width' => '50'),
                'sub_fields' => array(
                    array(
                        'key' => 'field_t4_footer_menu1_name',
                        'label' => 'name',
                        'name' => 'name',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_t4_footer_menu1_link',
                        'label' => 'link',
                        'name' => 'link',
                        'type' => 'url',
                    ),
                ),
            ),
            array(
                'key' => 'field_t4_footer_menu2',
                'label' => 'Footer menu2',
                'name' => 't4_footer_menu2',
                'type' => 'repeater',
                'layout' => 'table',
                'wrapper' => array('width' => '50'),
                'sub_fields' => array(
                    array(
                        'key' => 'field_t4_footer_menu2_name',
                        'label' => 'name',
                        'name' => 'name',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_t4_footer_menu2_link',
                        'label' => 'link',
                        'name' => 'link',
                        'type' => 'url',
                    ),
                ),
            ),
            array(
                'key' => 'field_t4_all_right',
                'label' => 'All right',
                'name' => 't4_all_right',
                'type' => 'textarea',
            ),
            
            // Fixed Casino Tab
            array(
                'key' => 'field_t4_fixed_casino_tab',
                'label' => 'Fixed casino',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_enable_disable',
                'label' => 'Enable/disable',
                'name' => 't4_enable_disable',
                'type' => 'checkbox',
                'choices' => array(
                    'Enable' => 'Enable',
                    'Disable' => 'Disable',
                ),
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_logo',
                'label' => 'Logo',
                'name' => 't4_fixed_logo',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_bg_fixed',
                'label' => 'Background popup',
                'name' => 't4_bg_fixed',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_title',
                'label' => 'Title',
                'name' => 't4_fixed_title',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_subtitle',
                'label' => 'Subtitle',
                'name' => 't4_fixed_subtitle',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_link',
                'label' => 'Link',
                'name' => 't4_fixed_link',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_btn_name',
                'label' => 'Btn',
                'name' => 't4_btn_name',
                'type' => 'text',
                'default_value' => 'Play Now',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_btn_bg',
                'label' => 'Background btn',
                'name' => 't4_fixed_btn_bg',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            
            // Fixed Casino Mobile Tab
            array(
                'key' => 'field_t4_fixed_casino_mobile_tab',
                'label' => 'Fixed casino mobile',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_enable_disable_mobile',
                'label' => 'Enable/disable',
                'name' => 't4_enable_disable_mobile',
                'type' => 'checkbox',
                'choices' => array(
                    'Enable' => 'Enable',
                    'Disable' => 'Disable',
                ),
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_logo_mobile',
                'label' => 'Logo',
                'name' => 't4_fixed_logo_mobile',
                'type' => 'image',
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_bg_fixed_mobile',
                'label' => 'Background popup',
                'name' => 't4_bg_fixed_mobile',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_title_mobile',
                'label' => 'Title',
                'name' => 't4_fixed_title_mobile',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_subtitle_mobile',
                'label' => 'Subtitle',
                'name' => 't4_fixed_subtitle_mobile',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_link_mobile',
                'label' => 'Link',
                'name' => 't4_fixed_link_mobile',
                'type' => 'text',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_btn_name_mobile',
                'label' => 'Btn',
                'name' => 't4_btn_name_mobile',
                'type' => 'text',
                'default_value' => 'Play Now',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_fixed_btn_bg_mobile',
                'label' => 'Background btn',
                'name' => 't4_fixed_btn_bg_mobile',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            
            // FAQ Tab
            array(
                'key' => 'field_t4_faq_tab',
                'label' => 'FAQ',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ),
            array(
                'key' => 'field_t4_faq_color',
                'label' => 'Faq color active',
                'name' => 't4_faq_color',
                'type' => 'color_picker',
                'wrapper' => array('width' => '33'),
            ),
            array(
                'key' => 'field_t4_faq_bg',
                'label' => 'Faq background',
                'name' => 't4_faq_bg',
                'type' => 'color_picker',
                'default_value' => '#eeeff4',
                'wrapper' => array('width' => '33'),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'template4-settings',
                ),
            ),
        ),
    ));
}
